### ISSUE TITLE
Graph incorrectly showing data when nightscout has missing data spots

### ISSUE THREAD

**Issue by legoandmars** [legoandmars/nightscout-chrome#10]
as it currently is, all gaps in nightscout data are ignored and every data point is moved to the farthest possible point right.
This should be fixed in order to ensure that the time on the bottom is correct.

**Comment by leogandmars** [comment]
This also happens when non-bloodsugar data points are present. For exampl

**Comment by legoandmars** [comment]
Fixed in graph rework (2.0.0)
